
if (SQLITE_INCLUDE_DIR AND SQLITE_LIBRARIES)
    set(Sqlite_FIND_QUIETLY TRUE)
endif (SQLITE_INCLUDE_DIR AND SQLITE_LIBRARIES)

if (NOT WIN32)
    find_package(PkgConfig)
    pkg_check_modules(PC_SQLITE sqlite3)
    set(SQLITE_DEFINITIONS ${PC_SQLITE_CFLAGS_OTHER})
endif (NOT WIN32)

find_path(SQLITE_INCLUDE_DIR NAMES sqlite3.h
    PATHS
    ${PC_SQLITE_INCLUDEDIR}
    ${PC_SQLITE_INCLUDE_DIRS}
)

find_library(SQLITE_LIBRARIES NAMES sqlite3
    PATHS
    ${PC_SQLITE_LIBDIR}
    ${PC_SQLITE_LIBRARY_DIRS}
)

include(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(Sqlite DEFAULT_MSG SQLITE_INCLUDE_DIR SQLITE_LIBRARIES)
mark_as_advanced(SQLITE_INCLUDE_DIR SQLITE_LIBRARIES)